version: 2

project_name: idl

builds:
  - id: idl
    main: ./cmd/idl
    binary: idl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - format: binary
    name_template: "idl_{{ .Os }}_{{ .Arch }}{{ if eq .Os \"windows\" }}.exe{{ end }}"

checksum:
  name_template: "checksums.txt"
